export default {
  currentPartial: 'MyProfile',
  currentMenu: '',
  userData: {
    userId: -1,
    employeeNumber: '',
    profileType: '',
    manager: '',
    email: '',
    userName: '',
    password: '',
    phone: '',
    company: '',
    field: '',
    role: '',
    emergencyFlag: false,
    vipFlag: false,
  },
  userStatus: [],
  pointOfSales: [],
  profileAccess: {},
}
